export const ListeProfession = {
  AUCUN_RESULTAT : 'Aucun resultat',
  ACCASTILLEUR : 'Accastilleur',
  ACCORDEUR_INSTRUMENTS_MUSIQUE : "Accordeur d'instruments de musique",
  ACTUAIRE : 'Actuaire',
  ACUPUNCTEUR : 'Acupuncteur',
  ACUPUNCTEUR_NON_MEDECIN : 'Acupuncteur non médecin',
  ADMINISTRATEUR_BIENS_SYNDIC : 'Administrateur de biens – Syndic',
  ADMINISTRATEUR_JUDICIAIRE : 'Administrateur judiciaire',
  AFFICHAGE : 'Affichage',
  AFFUTEUR : 'Affûteur',
  AGENT_COMMERCIAL : 'Agent commercial',
  AGENT_ASSURANCES : 'Agent d’assurances',
  AGENT_IMMOBILIER : 'Agent immobilier',
  AGENT_SPORTIF : 'Agent sportif',
  AGRICULTEUR : 'Agriculteur',
  AIDE_RELATIONNELLE : 'Aide Relationnelle (si psychologue ou psychothérapeute)',
  AIDE_A_DOMICILE : 'Aide à domicile',
  AIDE_A_LA_PERSONNE : 'Aide à la personne (nettoyage, entretien, petits travaux)',
  AJUSTEUR : 'Ajusteur',
  ALIMENTATION_GENERALE : 'Alimentation générale, vins, spiritueux',
  AMBULANCIER : 'Ambulancier',
  AMEUBLEMENT_DISTRIBUTEUR : 'Ameublement (distributeur)',
  ANALYSTE_INFORMATIQUE : 'Analyste en informatique',
  ANTIQUAIRE : 'Antiquaire',
  APICULTEUR : 'Apiculteur',
  APPROVISIONNEUR : 'Approvisionneur',
  ARCHETIER : 'Archetier',
  ARCHITECTE : 'Architecte',
  ARCHIVISTE : 'Archiviste',
  ARCHEOLOGUE : 'Archéologue',
  ARMURIER_FABRICATION : 'Armurier – fabrication',
  ARMURIER_VENTE : 'Armurier – vente',
  ARTICLE_PUERICULTURE : 'Article puériculture',
  ASCENSORISTE : 'Ascensoriste',
  ASSISTANTE_SOCIALE_LIBERAL : 'Assistante sociale à titre libéral',
  ATTACHE_DE_PRESSE : 'Attaché de presse',
  AUBERGISTE : 'Aubergiste',
  AUDIOLOGUE : 'Audiologue',
  AUDIOPROTHESISTE : 'Audioprothésiste',
  AUDITEUR : 'Auditeur',
  AUXILIAIRE_PUERICULTURE : 'Auxiliaire de puériculture',
  AUXILIAIRE_DE_VIE : 'Auxiliaire de vie',
  AVICULTEUR : 'Aviculteur',
  AVOCAT : 'Avocat',
  BAGAGISTE : 'Bagagiste',
  BARMAN : 'Barman',
  BIBLIOTHECAIRE : 'Bibliothécaire',
  BIJOUTIER_JOAILLIER : 'Bijoutier / joaillier',
  BIOLOGISTE : 'Biologiste',
  BIOLOGISTE_LABORATOIRE : 'Biologiste laboratoire analyses médicales',
  BLANCHISSEUR : 'Blanchisseur',
  BOUCHER_HORS_ABATTOIRS : 'Boucher – hors abattoirs',
  BOULANGER : 'Boulanger',
  BRASSEUR_GERANT : 'Brasserie – gérant',
  BRIQUETIER : 'Briquetier',
  BROCANTEUR : 'Brocanteur',
  BURALISTE : 'Buraliste',
  CAFETIER : 'Cafetier',
  CAMERAMAN_SANS_DEPLACEMENT_ETRANGER : "Caméraman sans déplacement à l'étranger",
  CANTONNIER : 'Cantonnier',
  CARDIOLOGUE : 'Cardiologue',
  CARISTE : 'Cariste',
  CARRELEUR : 'Carreleur',
  CARRELEUR_TRAVAUX_ECHAFAUDAGE : 'Carreleur avec travaux sur échafaudages',
  CARRIER : 'Carrier',
  CARROSSIER : 'Carrossier',
  CARTOGRAPHE : 'Cartographe',
  CAVISTE : 'Caviste',
  CHARCUTIER : 'Charcutier',
  CHARGE_MISSION_CONSEIL_AUDIT : 'Chargé de mission en conseil et audit',
  CHARPENTIER : 'Charpentier',
  CHAUDRONNIER : 'Chaudronnier',
  CHAUFFAGISTE : 'Chauffagiste',
  CHAUFFEUR_LIVREUR : 'Chauffeur livreur',
  CHEF_CHANTIER_BTP : 'Chef de chantier BTP',
  CHERCHEUR_CONTRACTUEL : 'Chercheur contractuel',
  CHERCHEUR_SCIENTIFIQUE : 'Chercheur scientifique',
  CHIROPRATICIEN : 'Chiropracteur',
  CHIRURGIEN : 'Chirurgien',
  CHIRURGIEN_DENTISTE : 'Chirurgien-dentiste',
  CHOCOLATIER : 'Chocolatier',
  COFFREUR : 'Coffreur',
  COIFFEUR : 'Coiffeur',
  COLORISTE_CONSEIL : 'Coloriste conseil',
  COMMERCE_GROS_BOIS_MATERIAUX : 'Commerce de gros, de bois et de matériaux de construction',
  COMMERCIAL_SEDENTAIRE : 'Commercial sédentaire',
  COMMERÇANT : 'Commerçant',
  COMMERÇANT_ALIMENTATION : 'Commerçant en Alimentation',
  COMMERÇANT_BOUTIQUE : 'Commerçant en boutique',
  COMMERÇANT_CREATION_ARTISTIQUE : 'Commerçant en création artistique',
  COMMERÇANT_HABILLEMENT : 'Commerçant en habillement',
  COMMERÇANT_HIFI : 'Commerçant en hi-fi',
  COMMERÇANT_JOUETS : 'Commerçant en jouets',
  COMMERÇANT_ELECTROMENAGER : 'Commerçant en électroménager',
  COMMISSAIRE_COMPTES : 'Commissaire aux comptes',
  COMMISSAIRE_PRISEUR : 'Commissaire-priseur',
  COMPTABLE : 'Comptable',
  CONCEPTEUR_REDACTEUR : 'Concepteur rédacteur',
  CONCESSIONNAIRE_AUTO : 'Concessionnaire auto',
  CONCIERGE_GARDIEN_IMMEUBLE : "Concierge/ gardien d'immeuble",
  CONCILIATEUR_ENTREPRISES_DIFFICULTES : 'Conciliateur pour entreprises en difficultés',
  CONDUCTEUR_ENGINS_BTP : 'Conducteur d’engins BTP',
  CONFISEUR : 'Confiseur',
  CONSEILLER_ARTISTIQUE : 'Conseiller artistique',
  CONSEILLER_COMMERCIAL : 'Conseiller commercial',
  CONSEILLER_CONJUGAL : 'Conseiller conjugal',
  CONSEILLER_ORIENTATION_PSYCHOLOGUE : "Conseiller d'orientation psychologue",
  CONSEILLER_EDUCATION : "Conseiller d'éducation",
  CONSEILLER_CLIENTELE : 'Conseiller de clientèle',
  CONSEILLER_DE_GESTION : 'Conseiller de gestion',
  CONSEILLER_SOCIETES : 'Conseiller de sociétés',
  CONSEILLER_ENTREPRISE : 'Conseiller d’entreprise',
  CONSEILLER_AFFAIRES : 'Conseiller en affaires et autres gestion',
  CONSEILLER_BREVETS : "Conseiller en brevets d'invention",
  CONSEILLER_COMMUNICATION : 'Conseiller en communication',
  CONSEILLER_CONSERVATION_PATRIMOINE : 'Conseiller en conservation du patrimoine',
  CONSEILLER_DECORATION : 'Conseiller en décoration',
  CONSEILLER_EXPANSION : 'Conseiller en expansion',
  CONSEILLER_FORMATION : 'Conseiller en formation',
  CONSEILLER_GESTION : 'Conseiller en gestion',
  CONSEILLER_GESTION_PATRIMOINE : 'Conseiller en gestion de patrimoine',
  CONSEILLER_GESTION_TUTELLE : 'Conseiller en gestion de tutelle',
  CONSEILLER_GESTION_FINANCIERE : 'Conseiller en gestion financière',
  CONSEILLER_IMMOBILIER : 'Conseiller en immobilier',
  CONSEILLER_IMPORTATION : 'Conseiller en importation',
  CONSEILLER_INFORMATIQUE : 'Conseiller en informatique',
  CONSEILLER_MANAGEMENT : 'Conseiller en management',
  CONSEILLER_MARKETING : 'Conseiller en marketing',
  CONSEILLER_OPTOMETRIE : 'Conseiller en optique',
  CONSEILLER_ORGANISATION : 'Conseiller en organisation',
  CONSEILLER_PRODUITS_REGIME : 'Conseiller en produits de régime',
  CONSEILLER_PUBLICITE : 'Conseiller en publicité',
  CONSEILLER_RECRUTEMENT : 'Conseiller en recrutement',
  CONSEILLER_RELATIONS_PUBLIQUES : 'Conseiller en relations publiques',
  CONSEILLER_RH : 'Conseiller en ressources humaines',
  CONSEILLER_STRATEGIE : 'Conseiller en stratégie',
  CONSEILLER_TRANSMISSION : 'Conseiller en transmission',
  CONSEILLER_TELEMATIQUE : 'Conseiller en télématique',
  CONSEILLER_ECONOMIE : 'Conseiller en économie',
  CONSEILLER_ERGONOME : 'Conseiller ergonome',
  CONSEILLER_FINANCIER : 'Conseiller financier',
  CONSEILLER_FISCAL : 'Conseiller fiscal',
  CONSEILLER_JURIDIQUE_FISCAL : 'Conseiller juridique fiscal',
  CONSEILLER_LITTERAIRE : 'Conseiller littéraire',
  CONSEILLER_LOGISTIQUE : 'Conseiller logistique',
  CONSEILLER_MATRIMONIAL : 'Conseiller matrimonial',
  CONSEILLER_QUALITE_COMPTABLE : 'Conseiller qualité comptable',
  CONSEILLER_SCIENTIFIQUE : 'Conseiller scientifique',
  CONSEILLER_SOCIAL : 'Conseiller social',
  CONSEILLER_TECHNIQUE : 'Conseiller technique',
  CONSEILLER_EDITORIAL : 'Conseiller éditorial',
  CONSTRUCTEUR_NAVAL : 'Constructeur naval',
  CONSULTANT : 'Consultant',
  CONTROLEUR_GESTION : 'Contrôleur de gestion',
  COORDINATION_CHANTIERS : 'Coordination de chantiers',
  COORDINATION_TRAVAUX : 'Coordination de travaux',
  CORDONNIER : 'Cordonnier',
  COURSIER : 'Coursier',
  COURTIER_ASSURANCES : 'Courtier d’assurances',
  COURTIER_CREDIT : 'Courtier en crédit',
  COURTIER_TRAVAUX : 'Courtier en travaux',
  COUTELLERIE : 'Coutellerie',
  COUTURIERE : 'Couturière',
  COUVREUR : 'Couvreur (travail en hauteur inférieur à 15 mètres)',
  CREATEUR_SITES_INTERNET : 'Créateur sites internet',
  CREMIER : 'Crémier',
  CUISINIER : 'Cuisinier',
  CUISINISTE : 'Cuisiniste',
  CULTIVATEUR : 'Cultivateur',
  CYCLES_COMMERCE_REPARATION : 'Cycles : commerce et réparation',
  CEREALIER : 'Céréalier',
  DENTISTE : 'Dentiste',
  DERMATOLOGUE : 'Dermatologue',
  DESIGNER : 'Designer',
  DESSINATEUR : 'Dessinateur',
  DIAGNOSTIQUEUR_IMMOBILIER : 'Diagnostiqueur immobilier',
  DIAMANTAIRE : 'Diamantaire',
  DISQUAIRE : 'Disquaire',
  DISTILLATEUR : 'Distillateur',
  DIETETICIEN : 'Diététicien',
  DOCUMENTALISTE : 'Documentaliste',
  DROGUISTE : 'Droguiste',
  DEBITANT_TABAC : 'Débitant de tabac',
  DECORATEUR : 'Décorateur',
  DECORATEUR_CONSEIL : 'Décorateur conseil',
  DECORATEUR_ENSEMBLIER : 'Décorateur ensemblier',
  DEPANNEUR : 'Dépanneur',
  EMBALLAGE_CONDITIONNEMENT : 'Emballage et conditionnement',
  ENCADREUR : 'Encadreur',
  ENSEIGNANT : 'Enseignant',
  ENTRAINEUR_ECHECS : 'Entraineur d’échecs',
  ENTREPRENEUR_BATIMENT : 'Entrepreneur en bâtiment',
  ENTRETIEN_PISCINES : 'Entretien de piscines',
  ERGONOME : 'Ergonome',
  ERGOTHERAPEUTE_LIBERAL : 'Ergothérapeute à titre libéral',
  ESTHETICIENNE : 'Esthéticienne',
  ESTHETIQUE_INDUSTRIELLE : 'Esthétique industrielle',
  ETHNOLOGUE : 'Ethnologue',
  EXPERT : 'Expert',
  EXPERT_AGRICOLE : 'Expert agricole',
  EXPERT_ASSUREUR : 'Expert assureur',
  EXPERT_AUTOMOBILE : 'Expert automobile',
  EXPERT_TABLEAUX : 'Expert de tableaux',
  EXPERT_ART_MOBILIER : 'Expert en art mobilier',
  EXPERT_ASSURANCES : 'Expert en assurances',
  EXPERT_BATIMENT : 'Expert en bâtiment',
  EXPERT_GRELE : 'Expert en grêle',
  EXPERT_OBJETS_ART : 'Expert en objets d’art',
  EXPERT_POLLUTION : 'Expert en pollution',
  EXPERT_ECRITURES : 'Expert en écritures',
  EXPERT_OEUVRES_ART : 'Expert en œuvres d’art',
  EXPERT_FINANCIER : 'Expert financier',
  EXPERT_FONCIER : 'Expert foncier',
  EXPERT_FORESTIER : 'Expert forestier',
  EXPERT_IMMOBILIER : 'Expert immobilier',
  EXPERT_JUDICIAIRE : 'Expert judiciaire',
  EXPERT_MARITIME : 'Expert maritime',
  EXPERT_PSYCHOLOGIQUE : 'Expert psychologique',
  EXPERT_TARIFICATEUR : 'Expert tarificateur',
  EXPERT_COMPTABLE : 'Expert-comptable',
  EXPLOITANT_AGRICOLE : 'Exploitant agricole',
  EXPLOITANT_STATION_SERVICE : 'Exploitant station-service',
  FABRICANT_INSTRUMENTS_MUSIQUE : "Fabricant d'instruments de musique",
  FABRICANT_OBJETS_PLASTIQUE_ETC : 'Fabricant d\'objets plastique, appareillage électrique, éléments béton etc.',
  FABRICANT_PAPIER_CARTONNAGE_EMBALLAGE : 'Fabricant de papier, cartonnage, emballage',
  FACTEUR : 'Facteur',
  FEMME_MENAGE : 'Femme de ménage',
  FERRONNIER : 'Ferronnier',
  FLEURISTE : 'Fleuriste',
  FONDEUR : 'Fondeur',
  FORGERON : 'Forgeron',
  FORMATEUR : 'Formateur',
  FORMATRICE_SECURITE_ROUTIERE : 'Formatrice en sécurité routière',
  FOURREUR : 'Fourreur',
  FRAISEUR : 'Fraiseur',
  FRIGORISTE : 'Frigoriste',
  FROMAGER : 'Fromager',
  FUMISTE : 'Fumiste',
  GARAGISTE : 'Garagiste',
  GARCON_CAFE : 'Garçon de café',
  GASTRO_ENTEROLOGUE : 'Gastro-entérologue',
  GRAPHISTE : 'Graphiste',
  GRAPHOLOGUE : 'Graphologue',
  GRAVEUR : 'Graveur',
  GRAVEUR_PIERRE : 'Graveur de la pierre (monuments funéraires ou autres)',
  GYNECOLOGUE : 'Gynécologue',
  GENEALOGISTE : 'Généalogiste',
  GEOLOGUE : 'Géologue (hors pétrole et gaz)',
  GEOMETRE : 'Géomètre',
  GEOMETRE_EXPERT : 'Géomètre expert',
  GEOPHYSICIEN : 'Géophysicien (hors pétrole/gaz/exploitation minière)',
  GERANT_HOLDING : 'Gérant de holding (si consultant ou conseil en gestion)',
  GERANT_MAGASIN : 'Gérant de magasin',
  GERANT_TUTELLE : 'Gérant de tutelle',
  GERANT_MAJORITAIRE_SCIERIE : 'Gérant Majoritaire de scierie',
  HERBORISTE : 'Herboriste',
  HORLOGER : 'Horloger',
  HORTICULTEUR : 'Horticulteur',
  HUISSIER_JUSTICE : 'Huissier de justice',
  HEBERGEMENT : 'Hébergement',
  HOTELIER : 'Hôtelier',
  HOTESSE_ACCUEIL : 'Hôtesse d\'accueil',
  HOTESSE_EXPOSITION : 'Hôtesse d’exposition',
  IMPRIMEUR : 'Imprimeur',
  INFOGRAPHISTE : 'Infographiste',
  INFORMATICIEN : 'Informaticien',
  INFORMATIQUE_SERVICES : 'Informatique (services, vente de matériel, logiciels)',
  INGENIEUR : 'Ingénieur',
  INGENIEUR_ADMINISTRATIF : 'Ingénieur administratif',
  INGENIEUR_AGRONOME : 'Ingénieur agronome',
  INGENIEUR_BUREAU : 'Ingénieur bureau',
  INGENIEUR_CHIMISTE : 'Ingénieur chimiste',
  INGENIEUR_COMMERCIAL : 'Ingénieur commercial',
  INGENIEUR_CONSEIL : 'Ingénieur conseil',
  INGENIEUR_CONSEIL_PLASTIQUE : 'Ingénieur conseil plastique',
  INGENIEUR_EAUX_FORETS : 'Ingénieur des eaux et des forêts',
  INGENIEUR_MINES : 'Ingénieur des mines',
  INGENIEUR_SON : 'Ingénieur du son',
  INGENIEUR_AFFAIRES : 'Ingénieur d’affaires',
  INGENIEUR_BTP_CHANTIER : 'Ingénieur en BTP avec déplacement sur chantier',
  INGENIEUR_INFORMATIQUE : 'Ingénieur en informatique',
  INGENIEUR_PRODUCTION : 'Ingénieur en production',
  INGENIEUR_MECANICIEN : 'Ingénieur mécanicien',
  INGENIEUR_THERMICIEN : 'Ingénieur thermicien',
  INSTALLATEUR_ARROSAGE_AUTOMATIQUE : 'Installateur d\'arrosage automatique',
  INSTALLATEUR_FIBRES_OPTIQUES : 'Installateur de fibres optiques',
  INSTALLATEUR_MAGASINS : 'Installateur de magasins',
  INSTALLATEUR_STORES : 'Installateur de stores',
  INSTALLATEUR_FRIGORIFIQUE : 'Installateur frigorifique',
  INSTALLATION_ENTRETIEN_ASCENSEURS : 'Installation et entretien d\'ascenseurs',
  INTERPRETE : 'Interprète',
  INTERPRETE_CONFERENCES : 'Interprète de conférences',
  INTERPRETE_GUIDE : 'Interprète guide',
  INTERPRETE_TRADUCTEUR : 'Interprète traducteur',
  ISOLATION_THERMIQUE_PHONIQUE : 'Isolation thermique et phonique',
  JARDINIER : 'Jardinier',
  JOAILLER : 'Joailler',
  JOURNALISTE : 'Journaliste sans déplacement à l\'étranger',
  JURISTE : 'Juriste',
  LABORANTIN : 'Laborantin',
  LAITIER : 'Laitier',
  LAVEUR_CARREAUX : 'Laveur de carreaux – immeubles (travail en hauteur inférieur à 15 mètres)',
  LAVEUR_VITRES : 'Laveur de vitres (vitrines, devantures)',
  LIBRAIRE : 'Libraire',
  LIQUIDATEUR_SOCIETE : 'Liquidateur de société',
  LIVREUR : 'Livreur',
  LIVREUR_COURSIER_MOTO : 'Livreur coursier à moto',
  LUTHIER : 'Luthier',
  MAGASINIER : 'Magasinier',
  MANDATAIRE_JUSTICE : 'Mandataire de justice',
  MANDATAIRE_SOCIETE : 'Mandataire de société',
  MANIPULATEUR_ELECTRORADIOLOGIE : 'Manipulateur en électroradiologie médicale',
  MANUCURE : 'Manucure',
  MANUTENTIONNAIRE : 'Manutentionnaire',
  MANOEUVRE_BTP : 'Manœuvre BTP',
  MAQUETTISTE : 'Maquettiste',
  MAQUIGNON : 'Maquignon',
  MARAICHER : 'Maraîcher',
  MARBRIER : 'Marbrier',
  MARCHAND_BESTIAUX : 'Marchand de bestiaux',
  MARCHAND_BIENS : 'Marchand de biens',
  MARCHAND_JOURNAUX : 'Marchand de journaux',
  MARCHAND_VINS : 'Marchand de vins',
  MARKETING : 'Marketing',
  MAROQUINIER : 'Maroquinier',
  MARECHAL_FERRAND : 'Maréchal ferrand',
  MATELASSIER : 'Matelassier',
  MACON : 'Maçon',
  MAITRE_OEUVRE : 'Maître d\'Œuvre',
  MAITRE_CONFERENCES : 'Maître de conférences',
  MAITRE_NAGEUR : 'Maître-nageur sauveteur en centre aquatique privé',
  MENUISERIE_ALUMINIUM : 'Menuiserie aluminium',
  MENUISIER : 'Menuisier',
  MERCHANDISEUR : 'Merchandiseur',
  MERCIER : 'Mercier',
  MINOTIER : 'Minotier',
  MIROITERIE : 'Miroiterie',
  MONITEUR_MOTO_ECOLE : 'Moniteur de moto-école',
  MONITEUR_AUTO_ECOLE : 'Moniteur d’auto-école',
  MONTEUR_ECHAFAUDAGE : 'Monteur d\'échafaudage',
  MONTEUR_CHARPENTES_METALLIQUES : 'Monteur de charpentes métalliques (travail en hauteur inférieur à 15 mètres)',
  MONTEUR_MECANIQUE : 'Monteur mécanique',
  MOTORISTE : 'Motoriste',
  MUSICIEN : 'Musicien',
  MYTILICULTEUR : 'Mytiliculteur',
  MECANICIEN_AUTOMOBILE : 'Mécanicien automobile',
  MECANICIEN_PRECISION : 'Mécanicien de précision',
  MECANICIEN_ENGINS_LOURDS : 'Mécanicien – engins lourds & machines agricoles',
  MECANICIEN_ENGINS_LEGERS : 'Mécanicien – engins légers',
  MECANIQUE_GENERALE : 'Mécanique générale',
  MECANOTHERAPIE : 'Mécanothérapie',
  MEDECIN : 'Médecin Généraliste ou Spécialiste',
  METALLURGISTE : 'Métallurgiste',
  METAYER : 'Métayer',
  METREUR : 'Métreur',
  METREUR_VERIFICATEUR : 'Métreur vérificateur',
  NATURALISTE_TAXIDERMISTE : 'Naturaliste/ taxidermiste',
  NATUROPATHE : 'Naturopathe',
  NETTOYAGE_ENTRETIEN : 'Nettoyage et entretien',
  NOTAIRE : 'Notaire',
  NOTEUR : 'Noteur',
  NOTEUR_COPISTE : 'Noteur copiste',
  NUTRITIONNISTE : 'Nutritionniste',
  NEGOCIANT_BOIS : 'Négociant en bois',
  NEGOCIANT_OBJETS_ART : 'Négociant en objets d’art',
  OBSTETRICIEN : 'Obstétricien',
  OCEANOGRAPHE : 'Océanographe',
  OFFICIER_MINISTERIEL : 'Officier ministériel',
  OPHTALMOLOGISTE : 'Ophtalmologiste',
  OPTICIEN : 'Opticien',
  OPERATEUR_SAISIE : 'Opérateur de saisie',
  ORTHODONTISTE : 'Orthodontiste',
  ORTHOPHONISTE : 'Orthophoniste',
  ORTHOPROTHESISTE : 'Orthoprothésiste',
  ORTHOPTISTE : 'Orthoptiste',
  ORTHOPEDISTE : 'Orthopédiste',
  OSTREICULTEUR : 'Ostréiculteur',
  OTO_RHINO_LARINGOLOGUE : 'Oto-rhino laringologue',
  OUTILLEUR : 'Outilleur',
  OUVRIER_AGRICOLE : 'Ouvrier agricole',
  OUVRIER_BTP : 'Ouvrier BTP',
  OUVRIER_FABRICATION_AUTOMOBILE : 'Ouvrier de fabrication automobile',
  OUVRIER_TEXTILE : 'Ouvrier textile',
  PAPETIER : 'Papetier',
  PARFUMEUR : 'Parfumeur',
  PAYSAGISTE : 'Paysagiste',
  PEINTRE_BATIMENT : 'Peintre en bâtiment',
  PEINTRE_INTERIEUR : 'Peintre intérieur',
  PEINTRE_VOITURE : 'Peintre voiture',
  PEINTRE_PLATRIER : 'Peintre-plâtrier',
  PHARMACIEN : 'Pharmacien',
  PHOTOGRAPHE : 'Photographe',
  PHYTOTHERAPEUTE : 'Phytothérapeute',
  PIGISTE_CORRESPONDANT_PRESSE : 'Pigiste – Correspondant de la presse écrite',
  PISCICULTEUR : 'Pisciculteur',
  PISCINISTE : 'Pisciniste',
  PLAQUISTE : 'Plaquiste',
  PLASTICIEN_CONSEIL : 'Plasticien conseil',
  PLOMBIER : 'Plombier',
  PLATRIER : 'Plâtrier',
  PNEUMOLOGUE : 'Pneumologue',
  PODO_ORTHESISTE : 'Podo-orthésiste',
  POISSONNIER : 'Poissonnier',
  POMPES_FUNEBRES : 'Pompes funèbres',
  POMPISTE : 'Pompiste',
  PORTEUR : 'Porteur',
  POSE_ALARME : 'Pose d\'alarme',
  POSE_EXTINCTEURS : 'Pose d\'extincteurs',
  POSEUR_ENSEIGNES : 'Poseur d\'enseignes',
  POSEUR_FENETRES : 'Poseur de fenêtres, volets roulants, portes',
  POSEUR_PARQUET : 'Poseur de parquet',
  POSEUR_REVETEMENTS_SOL : 'Poseur de revêtements de sol',
  POSEUR_ANTENNE_TV : 'Poseur d\'antenne TV (travail en hauteur inférieur à 15 mètres)',
  POTIER : 'Potier',
  PRESSING : 'Pressing',
  PRESTATAIRE_INFORMATIQUE : 'Prestataire en informatique',
  PRIMEURISTE : 'Primeuriste',
  PRODUCTEUR_LEGUMES : 'Producteur de légumes',
  PROFESSEUR : 'Professeur',
  PROFESSEUR_PRECEPTEUR : 'Professeur - Précepteur',
  PROFESSEUR_DANSE : 'Professeur de danse',
  PROFESSEUR_DESSIN : 'Professeur de dessin',
  PROFESSEUR_LANGUES : 'Professeur de langues',
  PROFESSEUR_MUSIQUE : 'Professeur de musique',
  PROFESSEUR_PIANO : 'Professeur de piano',
  PROFESSEUR_YOGA : 'Professeur de yoga',
  PROFESSIONNEL_PRODUCTION_CINEMA_TV : 'Professionnel Production cinéma télévision',
  PROGRAMMEUR : 'Programmeur',
  PROMOTEUR_IMMOBILIER : 'Promoteur immobilier',
  PROTECTION_INCENDIE : 'Protection incendie (création de produits de sécurité, installation et maintenance)',
  PROTHESISTE : 'Prothésiste',
  PROTHESISTE_DENTAIRE : 'Prothésiste dentaire',
  PREPARATEUR_PHARMACIE : 'Préparateur en pharmacie',
  PREPARATEUR_PHYSIQUE_DOMICILE : 'Préparateur physique à domicile',
  PSYCHANALYSTE : 'Psychanalyste',
  PSYCHIATRE : 'Psychiatre',
  PSYCHOLOGUE : 'Psychologue',
  PSYCHOLOGUE_CLINICIEN : 'Psychologue clinicien',
  PSYCHOMOTRICIEN : 'Psychomotricien',
  PSYCHOSOCIOLOGUE : 'Psychosociologue',
  PSYCHOTECHNICIEN : 'Psychotechnicien',
  PSYCHOTHERAPEUTE : 'Psychothérapeute',
  PUBLICITAIRE : 'Publicitaire',
  PUISTATIER : 'Puisatier',
  PUERICULTRICE : 'Puéricultrice',
  PATISSIER : 'Pâtissier',
  PEDIATRE : 'Pédiatre',
  PEDICURE_PODOLOGUE : 'Pédicure-podologue',
  PEPINIERISTE : 'Pépiniériste',
  QUINCAILLIER : 'Quincaillier',
  RADIOLOGUE : 'Radiologue',
  RAMONEUR : 'Ramoneur',
  RAVALEUR : 'Ravaleur',
  RELATION_PRESSE : 'Relation presse',
  RELATION_PUBLIQUES : 'Relation publiques',
  RELIEUR : 'Relieur',
  REPRESENTANT_VRP : 'Représentant – VRP',
  RESTAURATEUR : 'Restaurateur',
  RESTAURATEUR_ART : 'Restaurateur d\'art',
  RESTAURATEUR_MEUBLES_ANCIENS : 'Restaurateur de meubles anciens',
  RHUMATOLOGUE : 'Rhumatologue',
  REALISATEUR_PROGRAMME_TV : 'Réalisateur de programme TV',
  RECUPERATEUR : 'Récupérateur',
  REDACTEUR : 'Rédacteur',
  REDACTEUR_DOCUMENTALISTE : 'Rédacteur documentaliste',
  REDACTEUR_SCIENTIFIQUE : 'Rédacteur scientifique',
  REFLEXOLOGUE : 'Réflexologue',
  RENOVATEUR_APPARTEMENT : 'Rénovateur d’appartement',
  REPARATEUR_TV_ELECTROMENAGER : 'Réparateur TV, électroménager, appareils électroniques',
  REPARATION_AUTOMATISMES : 'Réparation / fabricant d’automatismes',
  SAGE_FEMME : 'Sage-femme',
  SCULPTEUR : 'Sculpteur',
  SCENARISTE : 'Scénariste',
  SECRETAIRE_INDEPENDANTE : 'Secrétaire indépendante',
  SERRURIER : 'Serrurier',
  SERVEUR : 'Serveur',
  SOCIOLOGUE : 'Sociologue',
  SOPHROLOGUE : 'Sophrologue',
  SOUDEUR : 'Soudeur',
  SOUFFLEUR_VERRE : 'Souffleur de verre',
  SPEAKER : 'Speaker',
  SPECIALISTE_TRANSPORT_MARITIME : 'Spécialiste du transport maritime',
  STANDARDISTE : 'Standardiste',
  STATISTICIEN : 'Statisticien',
  STOMATOLOGUE : 'Stomatologue',
  STYLISTE : 'Styliste',
  STENOTYPISTE_CONFERENCES : 'Sténotypiste de conférences',
  SYLVICULTEUR : 'Sylviculteur',
  TAILLEUR_VETEMENTS : 'Tailleur (vêtements)',
  TAILLEUR_PIERRES : 'Tailleur de pierres',
  TANNEUR : 'Tanneur',
  TAPISSIER : 'Tapissier',
  TECHNICIEN_AGRICOLE : 'Technicien agricole',
  TECHNICIEN_CONSEIL : 'Technicien conseil',
  TECHNICIEN_BIOLOGIE_MEDICALE : 'Technicien en biologie médicale',
  TECHNICIEN_COORDINATEUR_AIDE_PSYCHO_SOCIALE : 'Technicien-Coordinateur de l’aide psycho-sociale aux aidants',
  TEINTURIER : 'Teinturier',
  TERRASSIER : 'Terrassier',
  THERMICIEN : 'Thermicien',
  TISSERAND : 'Tisserand',
  TOILETTEUR_ANIMAUX : 'Toiletteur animaux',
  TOPOGRAPHE : 'Topographe',
  TOURNEUR : 'Tourneur',
  TRADUCTEUR : 'Traducteur',
  TRADUCTEUR_INTERPRETE : 'Traducteur interprète',
  TRADUCTEUR_TECHNIQUE : 'Traducteur technique',
  TRAITEUR : 'Traiteur',
  TRANSCRIPTEUR : 'Transcripteur',
  TRAVAUX_BIBLIOGRAPHIQUES : 'Travaux bibliographiques',
  TRAVAUX_INFORMATIQUES : 'Travaux informatiques',
  TRAVAUX_TELEMATIQUES : 'Travaux télématiques',
  TRIPIER : 'Tripier',
  TUYAUTEUR : 'Tuyauteur',
  TYPOGRAPHE : 'Typographe',
  TELECONSEILLER : 'Téléconseiller',
  TELEMARKETEUR : 'Télémarketeur',
  TOLIER : 'Tôlier',
  URBANISTE : 'Urbaniste',
  VENDEUR_CHEVAUX : 'Vendeur de chevaux',
  VENDEUR_BOUTIQUE : 'Vendeur en boutique',
  VITICULTEUR : 'Viticulteur',
  VITRIER : 'Vitrier',
  VULCANOLOGUE : 'Vulcanologue',
  VERIFICATEUR_MONUMENTS_HISTORIQUES : 'Vérificateur de monuments historiques',
  VETERINAIRE : 'Vétérinaire',
  ZINGUEUR : 'Zingueur',
  EBENISTE : 'Ébéniste',
  EBENISTERIE_ART : 'Ébénisterie d\'art',
  ECONOMISTE : 'Économiste',
  ECONOMISTE_CONSEIL : 'Économiste conseil',
  ECONOMISTE_CONSULTANT : 'Économiste consultant',
  ECONOMISTE_CONSTRUCTION : 'Économiste de la construction',
  ECRIVAIN_PUBLIC : 'Écrivain public',
  ECUYER : 'Écuyer',
  EDITEUR : 'Éditeur',
  EDUCATEUR : 'Éducateur',
  EDUCATEUR_DRESSEUR_CANIN : 'Éducateur, dresseur canin',
  ELECTRICIEN_BASSE_TENSION : 'Électricien - basse tension',
  ELECTRICIEN_AUTO : 'Électricien auto',
  ELECTRICIEN_HAUTE_TENSION : 'Électricien haute tension',
  ELECTROMECANICIEN_PRECISION : 'Électromécanicien - mécanique de précision',
  ELECTRONICIEN : 'Électronicien',
  ELEVEUR : 'Éleveur',
  ELEVEUR_CHEVAUX : 'Éleveur de chevaux',
  EPICIER : 'Épicier',
  ETALAGISTE_DECORATEUR : 'Étalagiste-décorateur',
  ETANCHEUR : 'Étancheur',
  ETANCHEISTE : 'Étanchéiste',
  ETUDES_MARCHES : 'Études de marchés',
  ETUDES_STRUCTURES : 'Études des structures',
  ETUDES_ENVIRONNEMENT : 'Études d’environnement',
  ETUDES_CONCEPTION : 'Études en conception',
  ETUDES_NUTRITION : 'Études en nutrition',
  ETUDES_CONSEILS : 'Études et conseils',
  ETUDES_DEVELOPPEMENT : 'Études et développement',
  ETUDES_RECHERCHES_TEXTILES : 'Études et recherches en textiles',
  ETUDES_EXPERTISES : 'Études expertises',
  ETUDES_HISTORIQUES_PATRIMOINE : 'Études historiques sur le patrimoine',
  ETUDES_INFORMATIQUES : 'Études informatiques',
  ETUDES_SOCIOLOGIQUES : 'Études sociologiques',
  ETUDES_STATISTIQUES : 'Études statistiques',
  ETUDES_STATISTIQUES_ECONOMIQUES : 'Études statistiques et économiques',
  ETUDES_TECHNIQUES : 'Études techniques',
  ETUDES_ELECTRONIQUES : 'Études électroniques',
  OENOLOGUE : 'Œnologue'
};

