export const ListePays = {
    Afghanistan : "Afghanistan",
    Albanie : "Albanie",
    Algerie : "Algerie",
    Andore : "Andore",
    Angola : "Angola",
    AntiguaAndBarbuda : "Antigua and Barbuda",
    Argentine : "Argentine",
    Armenie : "Armenie",
    Australie : "Australie",
    Austriche : "Austriche",
    Azerbaijan : "Azerbaijan",
    Bahamas : "Bahamas",
    Bahrain : "Bahrain",
    Bangladesh : "Bangladesh",
    Barbados : "Barbados",
    Bielorussie : "Bielorussie",
    Belgique : "Belgique",
    Belize : "Belize",
    Benin : "Benin",
    Bhutan : "Bhutan",
    Bolivia : "Bolivia",
    BosniaAndHerzegovina : "Bosnia and Herzegovina",
    Botswana : "Botswana",
    Brezil : "Brezil",
    Brunei : "Brunei",
    Bulgarie : "Bulgarie",
    BurkinaFaso : "Burkina Faso",
    Burundi : "Burundi",
    CaboVerde : "Cabo Verde",
    Cambodia : "Cambodia",
    Cameroon : "Cameroon",
    Canada : "Canada",
    CentralAfricanRepublic : "Central African Republic",
    Chad : "Chad",
    Chile : "Chile",
    China : "China",
    Colombia : "Colombia",
    Comoros : "Comoros",
    CongoBrazzaville : "Congo (Brazzaville)",
    CongoKinshasa : "Congo (Kinshasa)",
    CostaRica : "Costa Rica",
    Croatia : "Croatia",
    Cuba : "Cuba",
    Cyprus : "Cyprus",
    Czechia : "Czechia",
    Denmark : "Denmark",
    Djibouti : "Djibouti",
    Dominica : "Dominica",
    DominicanRepublic : "Dominican Republic",
    EastTimor : "East Timor",
    Ecuador : "Ecuador",
    Egypt : "Egypt",
    ElSalvador : "El Salvador",
    EquatorialGuinea : "Equatorial Guinea",
    Eritrea : "Eritrea",
    Estonia : "Estonia",
    Eswatini : "Eswatini",
    Ethiopia : "Ethiopia",
    Fiji : "Fiji",
    Finland : "Finland",
    France : "France",
    Gabon : "Gabon",
    Gambia : "Gambia",
    Georgia : "Georgia",
    Germany : "Germany",
    Ghana : "Ghana",
    Greece : "Greece",
    Grenada : "Grenada",
    Guatemala : "Guatemala",
    Guinea : "Guinea",
    GuineaBissau : "Guinea-Bissau",
    Guyana : "Guyana",
    Haiti : "Haiti",
    Honduras : "Honduras",
    Hungary : "Hungary",
    Iceland : "Iceland",
    India : "India",
    Indonesia : "Indonesia",
    Iran : "Iran",
    Iraq : "Iraq",
    Ireland : "Ireland",
    Israel : "Israel",
    Italy : "Italy",
    Jamaica : "Jamaica",
    Japan : "Japan",
    Jordan : "Jordan",
    Kazakhstan : "Kazakhstan",
    Kenya : "Kenya",
    Kiribati : "Kiribati",
    KoreaNorth : "Korea, North",
    KoreaSouth : "Korea, South",
    Kosovo : "Kosovo",
    Kuwait : "Kuwait",
    Kyrgyzstan : "Kyrgyzstan",
    Laos : "Laos",
    Latvia : "Latvia",
    Lebanon : "Lebanon",
    Lesotho : "Lesotho",
    Liberia : "Liberia",
    Libya : "Libya",
    Liechtenstein : "Liechtenstein",
    Lithuania : "Lithuania",
    Luxembourg : "Luxembourg",
    Madagascar : "Madagascar",
    Malawi : "Malawi",
    Malaysia : "Malaysia",
    Maldives : "Maldives",
    Mali : "Mali",
    Malta : "Malta",
    MarshallIslands : "Marshall Islands",
    Mauritania : "Mauritania",
    Mauritius : "Mauritius",
    Mexico : "Mexico",
    Micronesia : "Micronesia",
    Moldova : "Moldova",
    Monaco : "Monaco",
    Mongolia : "Mongolia",
    Montenegro : "Montenegro",
    Morocco : "Morocco",
    Mozambique : "Mozambique",
    Myanmar : "Myanmar",
    Namibia : "Namibia",
    Nauru : "Nauru",
    Nepal : "Nepal",
    Netherlands : "Netherlands",
    NewZealand : "New Zealand",
    Nicaragua : "Nicaragua",
    Niger : "Niger",
    Nigeria : "Nigeria",
    NorthMacedonia : "North Macedonia",
    Norway : "Norway",
    Oman : "Oman",
    Pakistan : "Pakistan",
    Palau : "Palau",
    Panama : "Panama",
    PapuaNewGuinea : "Papua New Guinea",
    Paraguay : "Paraguay",
    Peru : "Peru",
    Philippines : "Philippines",
    Pologne : "Pologne",
    Portugal : "Portugal",
    Qatar : "Qatar",
    Romanie : "Romanie",
    Russie : "Russie",
    Rwanda : "Rwanda",
    SaintKittsAndNevis : "Saint Kitts and Nevis",
    SaintLucia : "Saint Lucia",
    SaintVincentAndTheGrenadines : "Saint Vincent and the Grenadines",
    Samoa : "Samoa",
    SanMarino : "San Marino",
    SaoTomeAndPrincipe : "Sao Tome and Principe",
    SaudiArabia : "Saudi Arabia",
    Senegal : "Senegal",
    Serbie : "Serbie",
    Seychelles : "Seychelles",
    SierraLeone : "Sierra Leone",
    Singapore : "Singapore",
    Slovakie : "Slovakie",
    Slovenie : "Slovenie",
    SolomonIslands : "Solomon Islands",
    Somalie : "Somalie",
    SouthAfrica : "Sud afrique",
    SudSoudan : "Sud soudan",
    Espagne : "espagne",
    SriLanka : "Sri Lanka",
    Soudan : "Soudan",
    Suriname : "Suriname",
    Swede : "Swede",
    Switzerland : "Switzerland",
    Syrie : "Syrie",
    Taiwan : "Taiwan",
    Tajikistan : "Tajikistan",
    Tanzanie : "Tanzanie",
    Thailand : "Thailand",
    Togo : "Togo",
    Tonga : "Tonga",
    TrinidadAndTobago : "Trinidad and Tobago",
    Tunisie : "Tunisie",
    Turkie : "Turkie",
    Turkmenistan : "Turkmenistan",
    Tuvalu : "Tuvalu",
    Uganda : "Uganda",
    Ukraine : "Ukraine",
    EmiratsArabeUnis : "Emirats arabe unis",
    UnitedKingdom : "United Kingdom",
    UnitedStates : "United States",
    Uruguay : "Uruguay",
    Uzbekistan : "Uzbekistan",
    Vanuatu : "Vanuatu",
    VaticanCity : "Vatican City",
    Venezuela : "Venezuela",
    Vietnam : "Vietnam",
    Yemen : "Yemen",
    Zambie : "Zambie",
    Zimbabwe : "Zimbabwe"
};

